"""Added delete metadata

Revision ID: 344c8add8f16
Revises: a2207f321289
Create Date: 2024-12-29 23:28:38.840230

"""
from alembic import op
import sqlalchemy as sa
from app.utils.db import JSONBType


# revision identifiers, used by Alembic.
revision = '344c8add8f16'
down_revision = 'a2207f321289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_data', JSONBType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_column('meta_data')

    # ### end Alembic commands ###
