"""Updated EmailJob and EmailDelivery models

Revision ID: 54c07d11e538
Revises: bf8c7bbe6fc5
Create Date: 2024-12-21 09:44:11.620114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.utils.db import JSONBType

# revision identifiers, used by Alembic.
revision = '54c07d11e538'
down_revision = 'bf8c7bbe6fc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smtp_configurations',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=512), nullable=False),
    sa.Column('use_tls', sa.Boolean(), nullable=True),
    sa.Column('from_email', sa.String(length=255), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('emails_sent_today', sa.Integer(), nullable=True),
    sa.Column('last_reset_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_test_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('smtp_configurations', schema=None) as batch_op:
        batch_op.create_index('idx_smtp_user_active', ['user_id', 'is_active'], unique=False)
        batch_op.create_index('idx_smtp_user_default', ['user_id', 'is_default'], unique=False)

    with op.batch_alter_table('email_deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_attempt', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.create_index('idx_delivery_status', ['job_id', 'status'], unique=False)
        batch_op.create_index('idx_delivery_tracking', ['tracking_id'], unique=False)

    with op.batch_alter_table('email_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('meta_data', JSONBType(), nullable=True))
        batch_op.add_column(sa.Column('error_details', JSONBType(), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.create_index('idx_job_status_priority', ['status', 'priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_jobs_priority'), ['priority'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('smtp_config')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smtp_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))

    with op.batch_alter_table('email_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_jobs_priority'))
        batch_op.drop_index('idx_job_status_priority')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('error_details')
        batch_op.drop_column('meta_data')
        batch_op.drop_column('priority')
        batch_op.drop_column('body')

    with op.batch_alter_table('email_deliveries', schema=None) as batch_op:
        batch_op.drop_index('idx_delivery_tracking')
        batch_op.drop_index('idx_delivery_status')
        batch_op.drop_column('last_attempt')
        batch_op.drop_column('attempts')

    with op.batch_alter_table('smtp_configurations', schema=None) as batch_op:
        batch_op.drop_index('idx_smtp_user_default')
        batch_op.drop_index('idx_smtp_user_active')

    op.drop_table('smtp_configurations')
    # ### end Alembic commands ###
