"""Added template statistics

Revision ID: 763593956aef
Revises: bb710496e3d5
Create Date: 2024-12-28 09:13:11.386757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '763593956aef'
down_revision = 'bb710496e3d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_stats',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('total_sends', sa.Integer(), nullable=True),
    sa.Column('successful_sends', sa.Integer(), nullable=True),
    sa.Column('failed_sends', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('base_template_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('change_summary', sa.String(length=500), nullable=True))
        batch_op.create_index('idx_template_active_version', ['base_template_id', 'is_active', 'version'], unique=False)
        batch_op.create_index(batch_op.f('ix_templates_category'), ['category'], unique=False)
        batch_op.create_unique_constraint('uq_template_version', ['base_template_id', 'version'])
        batch_op.create_foreign_key(None, 'templates', ['parent_id'], ['id'])
        batch_op.drop_column('variables')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variables', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_template_version', type_='unique')
        batch_op.drop_index(batch_op.f('ix_templates_category'))
        batch_op.drop_index('idx_template_active_version')
        batch_op.drop_column('change_summary')
        batch_op.drop_column('published_at')
        batch_op.drop_column('base_template_id')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('tags')
        batch_op.drop_column('category')

    op.drop_table('template_stats')
    # ### end Alembic commands ###
