"""Add proper email job relationships

Revision ID: bb710496e3d5
Revises: 54c07d11e538
Create Date: 2024-12-21 10:04:50.448699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb710496e3d5'
down_revision = '54c07d11e538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smtp_config_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'smtp_configurations', ['smtp_config_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_jobs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('smtp_config_id')

    # ### end Alembic commands ###
