"""Added name field to user

Revision ID: bf8c7bbe6fc5
Revises: d54bd80f220d
Create Date: 2024-12-21 00:56:23.078783

"""
from alembic import op
import sqlalchemy as sa
from app.utils.db import ArrayType


# revision identifiers, used by Alembic.
revision = 'bf8c7bbe6fc5'
down_revision = 'd54bd80f220d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhooks',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('url', sa.String(length=500), nullable=False),
                    sa.Column('description', sa.String(
                        length=255), nullable=True),
                    sa.Column('events', ArrayType(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('secret', sa.String(length=100), nullable=True),
                    sa.Column('last_triggered_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('failure_count', sa.Integer(), nullable=True),
                    sa.Column('last_failure_reason', sa.Text(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(
                        timezone=True), nullable=True),
                    sa.Column('updated_at', sa.TIMESTAMP(
                        timezone=True), nullable=True),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('updated_by', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.create_index('idx_webhook_events', [
                              'events'], unique=False, postgresql_using='gin')
        batch_op.create_index(batch_op.f('ix_webhooks_user_id'), [
                              'user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhooks_user_id'))
        batch_op.drop_index('idx_webhook_events', postgresql_using='gin')

    op.drop_table('webhooks')
    # ### end Alembic commands ###
