"""[Models𝌭] Store refresh token & add email verification

Revision ID: d0c1794da997
Revises: f7472a04b6a9
Create Date: 2024-12-17 16:16:16.030439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c1794da997'
down_revision = 'f7472a04b6a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('refresh_token_expires', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('verification_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('verification_token_expires', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.alter_column('reset_token',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_users_email_verified'), ['email_verified'], unique=False)
        batch_op.create_unique_constraint(None, ['refresh_token'])
        batch_op.create_unique_constraint(None, ['verification_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_email_verified'))
        batch_op.alter_column('reset_token',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('verification_token_expires')
        batch_op.drop_column('verification_token')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('refresh_token_expires')
        batch_op.drop_column('refresh_token')

    # ### end Alembic commands ###
