"""Improved template versioning.

Revision ID: e71facde486c
Revises: f3d4bd1738fa
Create Date: 2025-01-09 04:58:37.570847

"""
from alembic import op
import sqlalchemy as sa
from app.utils.db import JSONBType


# revision identifiers, used by Alembic.
revision = 'e71facde486c'
down_revision = 'f3d4bd1738fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_index('idx_template_active_version')
        batch_op.drop_constraint('uq_template_version', type_='unique')
        batch_op.drop_constraint('templates_parent_id_fkey', type_='foreignkey')
        batch_op.drop_column('change_summary')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('base_template_id')

    op.create_table('template_versions',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('change_summary', sa.String(length=500), nullable=True),
    sa.Column('meta_data', JSONBType(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'version', name='uq_template_version')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_template_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('change_summary', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('templates_parent_id_fkey', 'templates', ['parent_id'], ['id'])
        batch_op.create_unique_constraint('uq_template_version', ['base_template_id', 'version'])
        batch_op.create_index('idx_template_active_version', ['base_template_id', 'is_active', 'version'], unique=False)

    op.drop_table('template_versions')
    # ### end Alembic commands ###
