"""Improved template versioning.

Revision ID: f3428a7b8f8b
Revises: e71facde486c
Create Date: 2025-01-15 13:50:19.297847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3428a7b8f8b'
down_revision = 'e71facde486c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_versions', schema=None) as batch_op:
        batch_op.create_index('idx_template_versions_template_id_version', ['template_id', 'version'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_versions', schema=None) as batch_op:
        batch_op.drop_index('idx_template_versions_template_id_version')

    # ### end Alembic commands ###
